export enum PermissionType {
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_SUPER_ADMIN_DASHBOARD = 'VIEW_SUPER_ADMIN_DASHBOARD',
  VIEW_ADMIN_DASHBOARD = 'VIEW_ADMIN_DASHBOARD',
  VIEW_CUSTOMER_DASHBOARD = 'VIEW_CUSTOMER_DASHBOARD',
  MANGER_ROLES = 'MANGER_ROLES',
  MANAGE_EXPENSES = 'MANAGE_EXPENSES',
  MANAGE_SYSTEM_LISTS = 'MANAGE_SYSTEM_LISTS'
}
